# Generated by Django 5.0.6 on 2025-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fios',
            name='material',
            field=models.CharField(choices=[('cobre', 'Cobre'), ('aco', 'Aço')], default='cobre', max_length=20),
        ),
    ]
