# Generated by Django 5.0.6 on 2025-08-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_fios_date_added_fios_updated_at_po_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='reference',
            field=models.CharField(choices=[('0-0,25', '0-0,25'), ('0-0,50', '0-0,50'), ('0-1', '0-1'), ('0-2', '0-2'), ('2-4', '2-4'), ('4-8', '4-8'), ('6-12', '6-12'), ('10-20', '10-20'), ('20-40', '20-40'), ('40-60', '40-60'), ('60-80', '60-80'), ('2-6', '2-6'), ('5-10', '5-10'), ('0-0,20', '0-0,20')], max_length=10),
        ),
    ]
