# Generated by Django 5.2.5 on 2025-08-27 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_po_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.fornecedor'),
        ),
    ]
