# Generated by Django 5.2.5 on 2025-08-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_po_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='product',
            field=models.CharField(default='Pó de Diamante', max_length=40),
        ),
    ]
