# Generated by Django 5.0.6 on 2025-08-28 11:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_updatefios_updatepo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='updatepo',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], default='added', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updatepo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='updatepo',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='updatepo',
            name='new_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='updatepo',
            name='previous_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='updatepo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
