# Generated by Django 5.0.6 on 2025-08-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_updatepo_action_updatepo_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatepo',
            name='timestamp',
        ),
    ]
