# Generated by Django 5.0.6 on 2025-08-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_updatepo_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatefios',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], default='added', max_length=10),
            preserve_default=False,
        ),
    ]
