# Generated by Django 5.0.6 on 2025-08-29 11:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_poentradas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fioEntradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.fios')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fioSaidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('date_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.fios')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FioTransformacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_transferido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('peso_origem_antes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_origem_depois', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transformacoes_origem', to='management.fios')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FioTransformacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_adicionado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transformacoes_destino', to='management.fios')),
                ('transformacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='management.fiotransformacao')),
            ],
        ),
    ]
