# Generated by Django 5.2.5 on 2025-09-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='reference',
        ),
    ]
