# Generated by Django 5.2.5 on 2025-09-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_categoriaproduto_stock_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agulhas',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.fornecedor'),
        ),
        migrations.AlterField(
            model_name='fios',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.fornecedor'),
        ),
    ]
