# Generated by Django 5.0.6 on 2025-09-11 09:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_agulhas_fornecedor_alter_fios_fornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fios',
            name='weight_unit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='ref_fornecedor',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='FioUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=4, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.CharField(max_length=20)),
                ('quantidade_usada', models.PositiveIntegerField()),
                ('data_uso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.fios')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
