# Generated by Django 5.0.6 on 2025-10-16 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_fios_weight_unit_alter_fornecedor_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fios',
            name='min_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='stockMaquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=100)),
                ('production_equipment', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('defined_location', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('manual', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=10, null=True)),
                ('certificado_ce', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('manutenance_date', models.DateField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.fornecedor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
