# Generated by Django 5.0.6 on 2025-10-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_fios_min_stock_stockmaquinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
