# Generated by Django 5.0.6 on 2025-10-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_alter_fornecedor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockmaquinas',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stockmaquinas',
            name='defined_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockmaquinas',
            name='machine_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockmaquinas',
            name='model',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockmaquinas',
            name='production_equipment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockmaquinas',
            name='serial_number',
            field=models.CharField(max_length=200),
        ),
    ]
