# Generated by Django 5.0.6 on 2025-10-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_alter_fornecedor_nome_alter_stockmaquinas_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmaquinas',
            name='defined_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stockmaquinas',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stockmaquinas',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stockmaquinas',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
