# Generated by Django 5.0.6 on 2025-10-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_alter_stockmaquinas_defined_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmaquinas',
            name='machine_number',
            field=models.IntegerField(unique=True),
        ),
    ]
