# Generated by Django 5.0.6 on 2025-10-17 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_alter_stockmaquinas_machine_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='poentradas',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.updatepo'),
        ),
        migrations.AddField(
            model_name='posaidas',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.updatepo'),
        ),
    ]
