# Generated by Django 5.0.6 on 2025-10-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_poentradas_update_posaidas_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poentradas',
            name='update',
        ),
        migrations.RemoveField(
            model_name='posaidas',
            name='update',
        ),
        migrations.AddField(
            model_name='poentradas',
            name='previous_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posaidas',
            name='previous_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='updatepo',
            name='previous_quantity',
            field=models.IntegerField(),
        ),
    ]
