# Generated by Django 5.0.6 on 2025-10-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_remove_poentradas_update_remove_posaidas_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posaidas',
            name='previous_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='updatepo',
            name='previous_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
