# Generated by Django 5.0.6 on 2025-10-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_alter_posaidas_previous_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agulhasentradas',
            name='previous_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='agulhasentradas',
            name='stock_after_use',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='agulhassaidas',
            name='previous_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='agulhassaidas',
            name='stock_after_use',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fioentradas',
            name='previous_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fioentradas',
            name='stock_after_use',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fiosaidas',
            name='previous_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fiosaidas',
            name='stock_after_use',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='poentradas',
            name='stock_after_addition',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='posaidas',
            name='stock_after_use',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stocksaidas',
            name='previous_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stocksaidas',
            name='stock_after_use',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='updatestock',
            name='stock_after_use',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='poentradas',
            name='previous_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='updatestock',
            name='previous_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
