# Generated by Django 5.0.6 on 2025-10-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_agulhasentradas_previous_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fioentradas',
            name='stock_after_use',
        ),
        migrations.RemoveField(
            model_name='fiosaidas',
            name='stock_after_use',
        ),
        migrations.AddField(
            model_name='updatefios',
            name='stock_after_use',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
