# Generated by Django 5.0.6 on 2025-10-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_remove_fioentradas_stock_after_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiousado',
            name='stock_after_use',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
