# Generated by Django 5.0.6 on 2025-10-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_fiousado_stock_after_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentradas',
            name='previous_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stockentradas',
            name='stock_after_added',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
