# Generated by Django 5.0.6 on 2025-10-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_stockentradas_previous_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentradas',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stocksaidas',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
