# Generated by Django 5.0.6 on 2025-11-14 09:52

import management.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_stockentradas_descricao_stocksaidas_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agulhas',
            name='tamanho',
            field=management.models.FlexibleDecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fios',
            name='size',
            field=management.models.FlexibleDecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fios',
            name='weight',
            field=management.models.FlexibleDecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fios',
            name='weight_unit',
            field=management.models.FlexibleDecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fiotransformacao',
            name='peso_origem_antes',
            field=management.models.FlexibleDecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fiotransformacao',
            name='peso_origem_depois',
            field=management.models.FlexibleDecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fiotransformacao',
            name='total_transferido',
            field=management.models.FlexibleDecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fiotransformacaoitem',
            name='peso_adicionado',
            field=management.models.FlexibleDecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fiousado',
            name='size',
            field=management.models.FlexibleDecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fiousado',
            name='weight',
            field=management.models.FlexibleDecimalField(decimal_places=2, max_digits=10),
        ),
    ]
