# Generated by Django 5.0.6 on 2026-03-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_alter_agulhas_tamanho_alter_fios_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poentradas',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='posaidas',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
