# Generated by Django 5.0.6 on 2026-04-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_poentradas_fornecedor_posaidas_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='encomendado',
            field=models.BooleanField(default=False),
        ),
    ]
