# Generated by Django 5.0.6 on 2026-07-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_po_encomendado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateagulhas',
            name='agulha',
        ),
        migrations.RemoveField(
            model_name='updateagulhas',
            name='user',
        ),
        migrations.RemoveField(
            model_name='updatefios',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='updatefios',
            name='user',
        ),
        migrations.RemoveField(
            model_name='updatepo',
            name='po',
        ),
        migrations.RemoveField(
            model_name='updatepo',
            name='user',
        ),
        migrations.RenameField(
            model_name='fios',
            old_name='weight_unit',
            new_name='peso_minimo',
        ),
        migrations.RemoveField(
            model_name='fios',
            name='min_stock',
        ),
        migrations.DeleteModel(
            name='FioUsado',
        ),
        migrations.DeleteModel(
            name='UpdateAgulhas',
        ),
        migrations.DeleteModel(
            name='updateFios',
        ),
        migrations.DeleteModel(
            name='updatePo',
        ),
    ]
