# Generated by Django 5.0.6 on 2026-07-21 12:15

import management.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_remove_updateagulhas_agulha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fioentradas',
            name='quantity_added',
        ),
        migrations.RemoveField(
            model_name='fiosaidas',
            name='quantity_used',
        ),
        migrations.AddField(
            model_name='fioentradas',
            name='weight_added',
            field=management.models.FlexibleDecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiosaidas',
            name='weight_used',
            field=management.models.FlexibleDecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
